import mainThemeSrc from '../../assets/audio/01-tides-of-the-unarrived-dawn.mp3';
import mirajinHubSrc from '../../assets/audio/02-twilight-over-mirajin.mp3';
import saltglassExplorationSrc from '../../assets/audio/03-saltglass-horizon.mp3';
import kadelCitySrc from '../../assets/audio/04-inverted-harbor-of-kadel.mp3';
import fractureChaseSrc from '../../assets/audio/05-fracture-chase.mp3';
import battleSkirmishSrc from '../../assets/audio/06-bellshard-skirmish.mp3';
import orchardRevelationSrc from '../../assets/audio/07-whispers-beneath-the-orchard.mp3';
import bossEndingSrc from '../../assets/audio/08-abyssal-choir-reborn.mp3';

export const soundtrackTracks = Object.freeze([
  {
    id: 'main-theme',
    title: 'Tides Of The Unarrived Dawn',
    koreanTitle: '반향해 연대기 메인 테마',
    category: '타이틀 / 메인 테마',
    accent: 'gold',
    durationLabel: '1:50',
    chapters: '전체 공통',
    sceneUse: '타이틀, 핵심 컷신 회고, 메인 메뉴 대표곡',
    mood: '장엄한 바다 판타지, 비터스위트한 상실, 앞으로 나아가야 하는 의지',
    instrumentation: '현악, 피아노, 호른, 유리 질감 벨, 깊은 저역 퍼커션',
    summary: '세계관의 규모감과 플레이어의 책임감을 동시에 들려주는 대표 테마입니다.',
    src: mainThemeSrc,
    fileName: 'assets/audio/01-tides-of-the-unarrived-dawn.mp3',
  },
  {
    id: 'mirajin-hub',
    title: 'Twilight Over Mirajin',
    koreanTitle: '미라진 황혼 허브',
    category: '마을 / 허브 지역',
    accent: 'coral',
    durationLabel: '2:40',
    chapters: '프롤로그',
    sceneUse: '항구 조사, 출항 전 대화, 미라진 탐색',
    mood: '사라진 새벽의 정적, 조용한 죄책감, 아직 남아 있는 희망',
    instrumentation: '펠트 피아노, 저목관, 부드러운 현, 먼 종소리',
    summary: '영원한 황혼에 잠긴 항구의 쓸쓸함을 허브 탐색에 맞는 밀도로 정리한 곡입니다.',
    src: mirajinHubSrc,
    fileName: 'assets/audio/02-twilight-over-mirajin.mp3',
  },
  {
    id: 'glass-salt-exploration',
    title: 'Saltglass Horizon',
    koreanTitle: '유리염 사구 탐험',
    category: '탐험',
    accent: 'teal',
    durationLabel: '3:14',
    chapters: '챕터 1',
    sceneUse: '사구 필드 이동, 폐채굴 첨탑 전 탐험, 구조 동선 이동',
    mood: '황량함, 생존감, 묻힌 기억의 메아리, 넓은 수평선',
    instrumentation: '공기감 있는 현, 부드러운 타악, 유리성 타건, 낮은 첼로',
    summary: '미래가 메마른 땅의 공허함과 탐험 리듬을 함께 살리는 메인 필드 테마입니다.',
    src: saltglassExplorationSrc,
    fileName: 'assets/audio/03-saltglass-horizon.mp3',
  },
  {
    id: 'kadel-city',
    title: 'Inverted Harbor Of Kadel',
    koreanTitle: '역항도 카델',
    category: '도시 / 정치 긴장',
    accent: 'plum',
    durationLabel: '4:05',
    chapters: '챕터 2',
    sceneUse: '카델 진입, 도시 조사, 협상 이후 이동 구간',
    mood: '우아한 압박감, 불안한 균형, 규율의 아름다움과 냉기',
    instrumentation: '말렛 오스티나토, 절제된 브라스, 정교한 현, 기계 펄스',
    summary: '질서로 떠받친 도시의 위압감을 과도한 소음 없이 유지하도록 설계한 곡입니다.',
    src: kadelCitySrc,
    fileName: 'assets/audio/04-inverted-harbor-of-kadel.mp3',
  },
  {
    id: 'crisis-pursuit',
    title: 'Fracture Chase',
    koreanTitle: '붕괴 추적과 긴장',
    category: '긴장 / 추적',
    accent: 'slate',
    durationLabel: '3:20',
    chapters: '프롤로그, 챕터 1, 챕터 2, 엔딩',
    sceneUse: '시계탑 탈출, 구조전 직전, 카델 붕괴, 산호궁 붕괴 구간',
    mood: '급박한 이동, 무너지는 구조물, 사람을 먼저 구해야 하는 압력',
    instrumentation: '빠른 현 리듬, 깊은 탐, 절제된 신스 펄스, 짧은 금관 액센트',
    summary:
      '추격과 재난 상황에서 긴장을 끌어올리되 피로한 자극음으로 흐르지 않게 조정한 액션 트랙입니다.',
    src: fractureChaseSrc,
    fileName: 'assets/audio/05-fracture-chase.mp3',
  },
  {
    id: 'battle-skirmish',
    title: 'Bellshard Skirmish',
    koreanTitle: '일반 전투',
    category: '전투',
    accent: 'rose',
    durationLabel: '2:52',
    chapters: '전 챕터 공통',
    sceneUse: '일반 전투, 균열 생물 교전, 중간 보스 전 전반',
    mood: '전투 추진력, 영웅성, 비극의 그림자가 남아 있는 긴장감',
    instrumentation: '리듬 현, 브라스, 저역 타격, 어두운 드론',
    summary: '스토리 중심 RPG에 맞춰 추진력은 확보하되 과도한 공격성은 피한 공용 전투 곡입니다.',
    src: battleSkirmishSrc,
    fileName: 'assets/audio/06-bellshard-skirmish.mp3',
  },
  {
    id: 'orchard-revelation',
    title: 'Whispers Beneath The Orchard',
    koreanTitle: '감정 이벤트와 진실',
    category: '감정 이벤트',
    accent: 'teal',
    durationLabel: '3:05',
    chapters: '챕터 3',
    sceneUse: '속삭임 과수원, 사야 렌 고백, 척추탑 진실 공개',
    mood: '친밀감, 후회, 신뢰, 돌이킬 수 없는 진실의 무게',
    instrumentation: '피아노, 솔로 첼로, 하프, 유리 하모닉, 숨 쉬는 듯한 현',
    summary: '관계와 진실이 동시에 무너져 내리는 장면을 위해 설계한 감정 축 중심 테마입니다.',
    src: orchardRevelationSrc,
    fileName: 'assets/audio/07-whispers-beneath-the-orchard.mp3',
  },
  {
    id: 'boss-ending',
    title: 'Abyssal Choir Reborn',
    koreanTitle: '최종 결전과 엔딩',
    category: '보스전 / 엔딩',
    accent: 'gold',
    durationLabel: '3:05',
    chapters: '엔딩',
    sceneUse: '심연의 합창기 보스전, 마지막 선택, 엔딩 크레딧',
    mood: '압도적 결전, 세계의 무게, 비터스위트한 새벽과 후일담',
    instrumentation: '거대한 저현, 브라스, 깊은 종소리, 피아노, 열리는 현 합주',
    summary: '최종 보스전의 중압감에서 엔딩의 여운까지 한 곡 안에서 아우르는 대서사 트랙입니다.',
    src: bossEndingSrc,
    fileName: 'assets/audio/08-abyssal-choir-reborn.mp3',
  },
]);
