export const MODE_INTERVALS = Object.freeze({
  ionian: [0, 2, 4, 5, 7, 9, 11],
  dorian: [0, 2, 3, 5, 7, 9, 10],
  phrygian: [0, 1, 3, 5, 7, 8, 10],
  aeolian: [0, 2, 3, 5, 7, 8, 10],
  lydian: [0, 2, 4, 6, 7, 9, 11],
  mixolydian: [0, 2, 4, 5, 7, 9, 10],
});

const PALETTE_PRESETS = Object.freeze({
  dawn: Object.freeze({
    pad: { waveforms: ['triangle', 'sine'], gain: 0.03, filter: 1750, reverb: 0.4, delay: 0.1 },
    drone: { waveforms: ['sine'], gain: 0.018, filter: 540, reverb: 0.3, delay: 0 },
    bass: { waveforms: ['triangle', 'sine'], gain: 0.058, filter: 420, reverb: 0.06, delay: 0 },
    arp: { waveforms: ['sine', 'triangle'], gain: 0.018, filter: 2400, reverb: 0.28, delay: 0.18 },
    lead: { waveforms: ['sine', 'triangle'], gain: 0.02, filter: 2650, reverb: 0.35, delay: 0.2 },
    bell: { waveforms: ['sine'], gain: 0.018, filter: 3600, reverb: 0.65, delay: 0.22 },
  }),
  mist: Object.freeze({
    pad: { waveforms: ['sine', 'triangle'], gain: 0.026, filter: 1450, reverb: 0.45, delay: 0.08 },
    drone: { waveforms: ['sine'], gain: 0.022, filter: 400, reverb: 0.38, delay: 0 },
    bass: { waveforms: ['triangle'], gain: 0.054, filter: 340, reverb: 0.04, delay: 0 },
    arp: { waveforms: ['triangle'], gain: 0.016, filter: 1780, reverb: 0.32, delay: 0.12 },
    lead: { waveforms: ['sine'], gain: 0.018, filter: 2200, reverb: 0.42, delay: 0.16 },
    bell: { waveforms: ['sine'], gain: 0.016, filter: 3200, reverb: 0.7, delay: 0.18 },
  }),
  salt: Object.freeze({
    pad: { waveforms: ['triangle', 'sine'], gain: 0.028, filter: 1600, reverb: 0.26, delay: 0.06 },
    drone: { waveforms: ['triangle'], gain: 0.016, filter: 520, reverb: 0.18, delay: 0 },
    bass: { waveforms: ['triangle', 'square'], gain: 0.062, filter: 500, reverb: 0.04, delay: 0 },
    arp: { waveforms: ['triangle', 'square'], gain: 0.02, filter: 2100, reverb: 0.2, delay: 0.14 },
    lead: { waveforms: ['triangle', 'sine'], gain: 0.019, filter: 2420, reverb: 0.24, delay: 0.15 },
    bell: { waveforms: ['sine'], gain: 0.014, filter: 3400, reverb: 0.4, delay: 0.1 },
  }),
  inverse: Object.freeze({
    pad: { waveforms: ['triangle', 'sine'], gain: 0.026, filter: 1700, reverb: 0.24, delay: 0.1 },
    drone: { waveforms: ['triangle'], gain: 0.016, filter: 460, reverb: 0.15, delay: 0 },
    bass: { waveforms: ['triangle', 'square'], gain: 0.056, filter: 470, reverb: 0.03, delay: 0 },
    arp: { waveforms: ['triangle', 'sine'], gain: 0.018, filter: 2200, reverb: 0.18, delay: 0.2 },
    lead: { waveforms: ['triangle', 'sine'], gain: 0.018, filter: 2500, reverb: 0.24, delay: 0.18 },
    bell: { waveforms: ['sine'], gain: 0.013, filter: 3500, reverb: 0.48, delay: 0.16 },
  }),
  orchard: Object.freeze({
    pad: { waveforms: ['sine', 'triangle'], gain: 0.03, filter: 1900, reverb: 0.34, delay: 0.08 },
    drone: { waveforms: ['sine'], gain: 0.016, filter: 600, reverb: 0.24, delay: 0 },
    bass: { waveforms: ['triangle', 'sine'], gain: 0.052, filter: 450, reverb: 0.04, delay: 0 },
    arp: { waveforms: ['triangle', 'sine'], gain: 0.018, filter: 2350, reverb: 0.28, delay: 0.18 },
    lead: { waveforms: ['sine', 'triangle'], gain: 0.021, filter: 2750, reverb: 0.38, delay: 0.2 },
    bell: { waveforms: ['sine'], gain: 0.017, filter: 3700, reverb: 0.58, delay: 0.22 },
  }),
  tension: Object.freeze({
    pad: {
      waveforms: ['triangle', 'square'],
      gain: 0.024,
      filter: 1400,
      reverb: 0.18,
      delay: 0.05,
    },
    drone: { waveforms: ['triangle'], gain: 0.014, filter: 420, reverb: 0.1, delay: 0 },
    bass: { waveforms: ['square', 'triangle'], gain: 0.066, filter: 640, reverb: 0.02, delay: 0 },
    arp: { waveforms: ['square', 'triangle'], gain: 0.02, filter: 1950, reverb: 0.12, delay: 0.12 },
    lead: {
      waveforms: ['triangle', 'square'],
      gain: 0.021,
      filter: 2150,
      reverb: 0.18,
      delay: 0.12,
    },
    bell: { waveforms: ['sine'], gain: 0.012, filter: 3300, reverb: 0.28, delay: 0.08 },
  }),
  abyss: Object.freeze({
    pad: {
      waveforms: ['triangle', 'sawtooth'],
      gain: 0.028,
      filter: 1320,
      reverb: 0.36,
      delay: 0.06,
    },
    drone: { waveforms: ['sine', 'triangle'], gain: 0.02, filter: 360, reverb: 0.24, delay: 0 },
    bass: { waveforms: ['triangle', 'square'], gain: 0.066, filter: 410, reverb: 0.03, delay: 0 },
    arp: { waveforms: ['triangle', 'sine'], gain: 0.018, filter: 1720, reverb: 0.32, delay: 0.16 },
    lead: { waveforms: ['triangle', 'sine'], gain: 0.021, filter: 2050, reverb: 0.3, delay: 0.14 },
    bell: { waveforms: ['sine'], gain: 0.015, filter: 3000, reverb: 0.62, delay: 0.2 },
  }),
});

export const BASS_PATTERNS = Object.freeze({
  breath: ['root', null, null, null, 'fifth', null, null, null],
  harbor: ['root', null, 'fifth', null, 'root', null, 'approachUp', null],
  steps: ['root', null, 'fifth', 'root', 'root', null, 'octave', 'fifth'],
  descent: ['root', null, 'fifth', null, 'octave', 'fifth', 'approachDown', null],
  march: ['root', 'root', 'fifth', null, 'root', null, 'octave', 'fifth'],
  tide: ['root', null, 'root', 'fifth', 'octave', null, 'fifth', null],
  chase: ['root', 'fifth', 'root', 'octave', 'root', 'fifth', 'degree:1', 'fifth'],
  void: ['root', null, 'degree:1', null, 'fifth', null, 'degree:-1', null],
  ritual: ['root', null, null, 'fifth', 'root', null, 'degree:-1', null],
});

export const ARP_PATTERNS = Object.freeze({
  harborMist: ['scale:0', null, 'scale:2', null, 'chord:1', 'scale:4', null, 'scale:2'],
  ripple: ['chord:0', null, 'chord:1', 'scale:4', 'chord:2', null, 'scale:6', 'chord:1'],
  glass: ['chord:0', 'scale:2', null, 'chord:1', 'scale:4', 'scale:6', null, 'chord:2'],
  inverse: ['scale:6', 'chord:2', 'scale:4', 'chord:1', 'scale:2', 'chord:0', 'scale:2', 'chord:1'],
  orchard: ['scale:4', null, 'chord:1', 'scale:6', 'chord:2', null, 'scale:7', 'chord:1'],
  shards: ['chord:0', 'chord:1', 'scale:6', null, 'chord:2', 'scale:4', 'chord:1', null],
  choir: ['chord:0', null, 'chord:2', 'chord:1', 'scale:6', null, 'chord:2', 'scale:4'],
  pulse: ['chord:0', 'chord:1', 'chord:2', 'scale:4', 'chord:1', 'chord:2', 'scale:6', 'chord:1'],
  spiral: ['scale:7', 'scale:6', 'chord:2', 'scale:4', 'chord:1', 'scale:2', 'chord:0', 'scale:2'],
});

export const LEAD_PATTERNS = Object.freeze({
  theme: ['scale:0', null, 'scale:2', 'scale:4', 'scale:5', null, 'scale:4', 'scale:2'],
  question: ['scale:4', null, 'scale:2', 'scale:1', 'scale:0', null, 'scale:2', null],
  resolve: ['scale:2', 'scale:4', 'scale:5', null, 'scale:7', 'scale:5', 'scale:4', 'scale:0'],
  threat: ['degree:0', 'degree:1', null, 'degree:-1', 'degree:0', 'scale:6', null, 'scale:4'],
  lament: ['scale:5', null, 'scale:4', 'scale:2', 'scale:1', null, 'scale:0', null],
  horizon: ['scale:7', null, 'scale:9', 'scale:7', 'scale:5', null, 'scale:4', 'scale:2'],
  oath: ['degree:2', null, 'degree:1', 'degree:0', 'scale:4', null, 'scale:2', 'scale:0'],
  bloom: ['scale:4', 'scale:5', 'scale:7', null, 'scale:9', 'scale:7', 'scale:5', 'scale:4'],
  fracture: ['scale:7', null, 'scale:6', 'scale:4', 'scale:2', null, 'scale:1', 'scale:0'],
});

export const BELL_PATTERNS = Object.freeze({
  distant: ['scale:7', null, null, null, 'scale:4', null, null, null],
  glitter: ['scale:12', null, 'scale:9', null, 'scale:7', null, 'scale:9', null],
  omens: [null, 'degree:1', null, null, 'degree:-1', null, null, null],
  tears: ['scale:9', null, 'scale:7', null, 'scale:5', null, 'scale:4', null],
  ritual: ['scale:0', null, null, 'scale:7', null, null, 'scale:4', null],
});

export const DRUM_PATTERNS = Object.freeze({
  none: Object.freeze({ steps: 8, kick: [], snare: [], hat: [], low: [] }),
  softPulse: Object.freeze({
    steps: 8,
    kick: [0.72, 0, 0, 0, 0.42, 0, 0, 0],
    snare: [0, 0, 0, 0.18, 0, 0, 0, 0.24],
    hat: [0, 0.16, 0, 0.12, 0, 0.16, 0, 0.12],
    low: [],
  }),
  drift: Object.freeze({
    steps: 8,
    kick: [0.68, 0, 0.22, 0, 0.48, 0, 0.16, 0],
    snare: [0, 0, 0, 0.24, 0, 0, 0, 0.32],
    hat: [0, 0.12, 0.16, 0.12, 0, 0.12, 0.16, 0.12],
    low: [],
  }),
  chase: Object.freeze({
    steps: 16,
    kick: [0.92, 0, 0, 0, 0.64, 0, 0.24, 0, 0.84, 0, 0, 0, 0.72, 0, 0.3, 0],
    snare: [0, 0, 0, 0.22, 0, 0, 0, 0.36, 0, 0, 0, 0.18, 0, 0, 0, 0.44],
    hat: [0, 0.18, 0.22, 0.18, 0, 0.18, 0.22, 0.16, 0, 0.2, 0.24, 0.18, 0, 0.2, 0.28, 0.22],
    low: [],
  }),
  battle: Object.freeze({
    steps: 16,
    kick: [0.98, 0, 0.2, 0, 0.66, 0, 0.22, 0, 0.86, 0, 0.18, 0, 0.74, 0, 0.26, 0],
    snare: [0, 0, 0, 0.34, 0, 0, 0, 0.46, 0, 0, 0, 0.3, 0, 0, 0, 0.52],
    hat: [
      0, 0.24, 0.24, 0.18, 0.16, 0.24, 0.24, 0.18, 0.18, 0.24, 0.24, 0.18, 0.16, 0.24, 0.3, 0.24,
    ],
    low: [],
  }),
  boss: Object.freeze({
    steps: 16,
    kick: [1, 0, 0.22, 0, 0.72, 0, 0.3, 0, 0.92, 0, 0.2, 0, 0.82, 0, 0.34, 0],
    snare: [0, 0, 0, 0.38, 0, 0, 0, 0.5, 0, 0, 0, 0.32, 0, 0, 0, 0.58],
    hat: [
      0, 0.18, 0.24, 0.18, 0.12, 0.2, 0.26, 0.18, 0.14, 0.2, 0.24, 0.18, 0.12, 0.22, 0.32, 0.22,
    ],
    low: [0.48, 0, 0, 0, 0, 0, 0.32, 0, 0.42, 0, 0, 0, 0, 0, 0.38, 0],
  }),
  ritual: Object.freeze({
    steps: 8,
    kick: [0.82, 0, 0, 0.22, 0.56, 0, 0, 0.26],
    snare: [0, 0, 0, 0.16, 0, 0, 0, 0.24],
    hat: [0, 0.08, 0, 0.12, 0, 0.08, 0, 0.14],
    low: [0.34, 0, 0, 0, 0.22, 0, 0, 0],
  }),
  credits: Object.freeze({
    steps: 8,
    kick: [0.58, 0, 0, 0, 0.34, 0, 0, 0],
    snare: [0, 0, 0, 0.12, 0, 0, 0, 0.18],
    hat: [0, 0.12, 0, 0.1, 0, 0.12, 0, 0.1],
    low: [],
  }),
});

const TRACKS = [
  {
    id: 'title-dawn-tide',
    title: '새벽이 끊긴 바다',
    chapter: '타이틀 / 메인 테마',
    usage: '타이틀 화면, 세계 개요, 대표 라이트모티프',
    summary: '잔잔한 파도 위에 불길한 질문을 올리는 메인 테마다.',
    scene: '메인 테마',
    accent: 'teal',
    palette: 'dawn',
    tempo: 72,
    tonicMidi: 57,
    mode: 'dorian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'turn', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'harborMist',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 5,
        bass: 'harbor',
        arp: 'ripple',
        lead: 'theme',
        bell: 'glitter',
        drums: 'softPulse',
      },
      bridge: {
        degree: 3,
        bass: 'descent',
        arp: 'shards',
        lead: 'question',
        bell: 'omens',
        drums: 'none',
      },
      lift: {
        degree: 4,
        bass: 'tide',
        arp: 'pulse',
        lead: 'resolve',
        bell: 'glitter',
        drums: 'softPulse',
      },
      turn: {
        degree: 1,
        bass: 'breath',
        arp: 'inverse',
        lead: 'question',
        bell: 'distant',
        drums: 'none',
      },
      resolve: {
        degree: 0,
        bass: 'steps',
        arp: 'choir',
        lead: 'horizon',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
  {
    id: 'mirajin-harbor',
    title: '황혼의 미라진',
    chapter: '프롤로그 / 허브',
    usage: '미라진 항구 탐색, 정지된 일상, 첫 조사',
    summary: '아침이 사라진 항구의 멈춘 호흡과 죄책감을 낮게 깔아 준다.',
    scene: '프롤로그',
    accent: 'coral',
    palette: 'mist',
    tempo: 66,
    tonicMidi: 60,
    mode: 'aeolian',
    arrangement: ['intro', 'verse', 'turn', 'verse', 'bridge', 'verse', 'turn', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'harborMist',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 5,
        bass: 'harbor',
        arp: 'ripple',
        lead: 'lament',
        bell: 'distant',
        drums: 'none',
      },
      bridge: {
        degree: 3,
        bass: 'descent',
        arp: 'shards',
        lead: 'question',
        bell: 'omens',
        drums: 'softPulse',
      },
      turn: {
        degree: 4,
        bass: 'void',
        arp: 'harborMist',
        lead: null,
        bell: 'tears',
        drums: 'none',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'ripple',
        lead: 'question',
        bell: 'distant',
        drums: 'none',
      },
    },
  },
  {
    id: 'clocktower-echoes',
    title: '균열 시계탑',
    chapter: '프롤로그 / 탐험',
    usage: '시계탑 조사, 시간 균열, 백야 등장 장면',
    summary: '불길한 기계 잔향과 미스터리를 얇고 차갑게 움직인다.',
    scene: '프롤로그',
    accent: 'slate',
    palette: 'inverse',
    tempo: 84,
    tonicMidi: 50,
    mode: 'phrygian',
    arrangement: ['intro', 'verse', 'bridge', 'turn', 'verse', 'bridge', 'turn', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'inverse',
        lead: null,
        bell: 'omens',
        drums: 'none',
      },
      verse: {
        degree: 1,
        bass: 'void',
        arp: 'shards',
        lead: 'fracture',
        bell: 'distant',
        drums: 'softPulse',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'spiral',
        lead: 'question',
        bell: 'omens',
        drums: 'drift',
      },
      turn: { degree: 6, bass: 'void', arp: 'inverse', lead: null, bell: 'ritual', drums: 'none' },
      resolve: {
        degree: 0,
        bass: 'harbor',
        arp: 'choir',
        lead: 'threat',
        bell: 'omens',
        drums: 'drift',
      },
    },
  },
  {
    id: 'breakwater-run',
    title: '붕괴 방파제',
    chapter: '프롤로그 / 긴장',
    usage: '추격, 붕괴 탈출, 방파제 전투',
    summary: '숨이 붙은 채로 달리게 만드는 추격용 텐션 트랙이다.',
    scene: '프롤로그',
    accent: 'rose',
    palette: 'tension',
    tempo: 118,
    tonicMidi: 55,
    mode: 'phrygian',
    arrangement: ['intro', 'verse', 'lift', 'verse', 'bridge', 'verse', 'lift', 'resolve'],
    sections: {
      intro: { degree: 0, bass: 'march', arp: 'pulse', lead: null, bell: 'omens', drums: 'chase' },
      verse: {
        degree: 1,
        bass: 'chase',
        arp: 'shards',
        lead: 'threat',
        bell: null,
        drums: 'chase',
      },
      bridge: {
        degree: 6,
        bass: 'void',
        arp: 'inverse',
        lead: 'fracture',
        bell: 'omens',
        drums: 'battle',
      },
      lift: { degree: 4, bass: 'chase', arp: 'pulse', lead: 'oath', bell: null, drums: 'battle' },
      resolve: {
        degree: 0,
        bass: 'march',
        arp: 'shards',
        lead: 'resolve',
        bell: 'ritual',
        drums: 'battle',
      },
    },
  },
  {
    id: 'glasssalt-expanse',
    title: '유리염 사구',
    chapter: '챕터 1 / 탐험',
    usage: '사막 필드 탐험, 구조 이동, 폐채굴 접근',
    summary: '미래가 말라 버린 사막의 건조함과 먼 수평선을 함께 담는다.',
    scene: '챕터 1',
    accent: 'gold',
    palette: 'salt',
    tempo: 92,
    tonicMidi: 62,
    mode: 'lydian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'turn', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'glass',
        lead: null,
        bell: 'glitter',
        drums: 'none',
      },
      verse: {
        degree: 1,
        bass: 'steps',
        arp: 'glass',
        lead: 'theme',
        bell: 'distant',
        drums: 'drift',
      },
      bridge: {
        degree: 4,
        bass: 'descent',
        arp: 'ripple',
        lead: 'question',
        bell: 'tears',
        drums: 'none',
      },
      lift: {
        degree: 5,
        bass: 'tide',
        arp: 'pulse',
        lead: 'horizon',
        bell: 'glitter',
        drums: 'softPulse',
      },
      turn: {
        degree: 1,
        bass: 'harbor',
        arp: 'spiral',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      resolve: {
        degree: 0,
        bass: 'steps',
        arp: 'glass',
        lead: 'resolve',
        bell: 'glitter',
        drums: 'drift',
      },
    },
  },
  {
    id: 'rescue-line',
    title: '구조선 방어선',
    chapter: '챕터 1 / 전투',
    usage: '현장 구조전, 유리염 거신 직전 전투, 방어 라인 유지',
    summary: '현장 생존과 급박한 구조의 리듬을 공격적이지 않게 압축했다.',
    scene: '챕터 1',
    accent: 'coral',
    palette: 'tension',
    tempo: 126,
    tonicMidi: 60,
    mode: 'dorian',
    arrangement: ['intro', 'verse', 'verse', 'bridge', 'lift', 'verse', 'lift', 'resolve'],
    sections: {
      intro: { degree: 0, bass: 'march', arp: 'pulse', lead: null, bell: null, drums: 'battle' },
      verse: { degree: 3, bass: 'chase', arp: 'shards', lead: 'oath', bell: null, drums: 'battle' },
      bridge: {
        degree: 4,
        bass: 'descent',
        arp: 'spiral',
        lead: 'threat',
        bell: 'omens',
        drums: 'battle',
      },
      lift: { degree: 5, bass: 'chase', arp: 'pulse', lead: 'resolve', bell: null, drums: 'boss' },
      resolve: {
        degree: 0,
        bass: 'march',
        arp: 'shards',
        lead: 'theme',
        bell: 'ritual',
        drums: 'battle',
      },
    },
  },
  {
    id: 'kadel-updrift',
    title: '역항도 카델',
    chapter: '챕터 2 / 허브',
    usage: '거꾸로 선 항구, 협상, 도시 이동',
    summary: '도시의 경이와 불쾌한 질서감을 동시에 유지하는 중립 허브 음악이다.',
    scene: '챕터 2',
    accent: 'plum',
    palette: 'inverse',
    tempo: 102,
    tonicMidi: 64,
    mode: 'mixolydian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'turn', 'verse', 'lift', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'inverse',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 4,
        bass: 'steps',
        arp: 'inverse',
        lead: 'question',
        bell: 'glitter',
        drums: 'drift',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'spiral',
        lead: 'theme',
        bell: 'omens',
        drums: 'softPulse',
      },
      turn: { degree: 1, bass: 'void', arp: 'shards', lead: null, bell: 'ritual', drums: 'none' },
      lift: {
        degree: 6,
        bass: 'tide',
        arp: 'pulse',
        lead: 'oath',
        bell: 'glitter',
        drums: 'drift',
      },
      resolve: {
        degree: 0,
        bass: 'harbor',
        arp: 'inverse',
        lead: 'resolve',
        bell: 'distant',
        drums: 'drift',
      },
    },
  },
  {
    id: 'kadel-core-crisis',
    title: '역항 코어 붕괴',
    chapter: '챕터 2 / 전투',
    usage: '중력 반전 전투, 시민 보호전, 역추자 보스전',
    summary: '정치적 긴장과 물리적 붕괴를 빠른 박자로 겹쳐 놓은 전투곡이다.',
    scene: '챕터 2',
    accent: 'slate',
    palette: 'tension',
    tempo: 134,
    tonicMidi: 58,
    mode: 'aeolian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'lift', 'resolve'],
    sections: {
      intro: { degree: 0, bass: 'march', arp: 'pulse', lead: null, bell: null, drums: 'battle' },
      verse: {
        degree: 5,
        bass: 'chase',
        arp: 'inverse',
        lead: 'threat',
        bell: null,
        drums: 'battle',
      },
      bridge: {
        degree: 3,
        bass: 'descent',
        arp: 'spiral',
        lead: 'fracture',
        bell: 'omens',
        drums: 'boss',
      },
      lift: { degree: 4, bass: 'chase', arp: 'pulse', lead: 'oath', bell: null, drums: 'boss' },
      resolve: {
        degree: 0,
        bass: 'march',
        arp: 'shards',
        lead: 'resolve',
        bell: 'ritual',
        drums: 'boss',
      },
    },
  },
  {
    id: 'whispering-orchard',
    title: '속삭임 과수원',
    chapter: '챕터 3 / 탐험',
    usage: '과수원 조사, 감정 단서 수집, 사야와의 긴장',
    summary: '따뜻하지만 안정되지 않는 친밀감과 불안이 동시에 흐른다.',
    scene: '챕터 3',
    accent: 'teal',
    palette: 'orchard',
    tempo: 76,
    tonicMidi: 65,
    mode: 'lydian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'turn', 'verse', 'lift', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'orchard',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 4,
        bass: 'harbor',
        arp: 'orchard',
        lead: 'bloom',
        bell: 'tears',
        drums: 'softPulse',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'choir',
        lead: 'lament',
        bell: 'distant',
        drums: 'none',
      },
      turn: {
        degree: 1,
        bass: 'void',
        arp: 'harborMist',
        lead: 'question',
        bell: 'omens',
        drums: 'none',
      },
      lift: {
        degree: 6,
        bass: 'steps',
        arp: 'ripple',
        lead: 'theme',
        bell: 'glitter',
        drums: 'softPulse',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'orchard',
        lead: 'resolve',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
  {
    id: 'spine-tower-memory',
    title: '척추탑의 기억',
    chapter: '챕터 3 / 진실',
    usage: '진실 공개, 플레이어 정체성, 무도서고 탐색',
    summary: '정보 폭로를 소란스럽게 하지 않고 가라앉는 충격으로 밀어 넣는다.',
    scene: '챕터 3',
    accent: 'rose',
    palette: 'abyss',
    tempo: 68,
    tonicMidi: 55,
    mode: 'aeolian',
    arrangement: ['intro', 'verse', 'bridge', 'turn', 'verse', 'bridge', 'lift', 'resolve'],
    sections: {
      intro: { degree: 0, bass: 'ritual', arp: 'choir', lead: null, bell: 'ritual', drums: 'none' },
      verse: {
        degree: 5,
        bass: 'void',
        arp: 'choir',
        lead: 'lament',
        bell: 'tears',
        drums: 'none',
      },
      bridge: {
        degree: 3,
        bass: 'descent',
        arp: 'spiral',
        lead: 'fracture',
        bell: 'omens',
        drums: 'ritual',
      },
      turn: { degree: 1, bass: 'void', arp: 'shards', lead: null, bell: 'ritual', drums: 'none' },
      lift: { degree: 4, bass: 'tide', arp: 'pulse', lead: 'oath', bell: 'tears', drums: 'ritual' },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'question',
        bell: 'ritual',
        drums: 'none',
      },
    },
  },
  {
    id: 'silhouette-duel',
    title: '실루엣 대치',
    chapter: '챕터 3 / 대치',
    usage: '플레이어 실루엣 대치, 후회목 보스, 자기혐오 폭발',
    summary: '적과 자기 자신이 겹쳐 보이는 감정을 전투 템포로 묶는다.',
    scene: '챕터 3',
    accent: 'coral',
    palette: 'tension',
    tempo: 116,
    tonicMidi: 57,
    mode: 'phrygian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'turn', 'lift', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'march',
        arp: 'shards',
        lead: null,
        bell: 'omens',
        drums: 'battle',
      },
      verse: {
        degree: 1,
        bass: 'chase',
        arp: 'pulse',
        lead: 'fracture',
        bell: null,
        drums: 'battle',
      },
      bridge: {
        degree: 6,
        bass: 'void',
        arp: 'inverse',
        lead: 'threat',
        bell: 'omens',
        drums: 'boss',
      },
      turn: {
        degree: 5,
        bass: 'descent',
        arp: 'spiral',
        lead: 'question',
        bell: null,
        drums: 'battle',
      },
      lift: { degree: 4, bass: 'chase', arp: 'pulse', lead: 'oath', bell: null, drums: 'boss' },
      resolve: {
        degree: 0,
        bass: 'march',
        arp: 'shards',
        lead: 'resolve',
        bell: 'ritual',
        drums: 'boss',
      },
    },
  },
  {
    id: 'coral-descent',
    title: '침묵 산호궁',
    chapter: '엔딩 / 최종 던전',
    usage: '심해 산호궁 탐험, 마지막 항해, 분리 구간',
    summary: '깊고 젖은 공간감으로 결전 직전의 침묵을 붙잡는다.',
    scene: '엔딩',
    accent: 'slate',
    palette: 'abyss',
    tempo: 82,
    tonicMidi: 53,
    mode: 'dorian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'turn', 'verse', 'lift', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'ritual',
        arp: 'choir',
        lead: null,
        bell: 'ritual',
        drums: 'ritual',
      },
      verse: {
        degree: 5,
        bass: 'tide',
        arp: 'choir',
        lead: 'lament',
        bell: 'distant',
        drums: 'ritual',
      },
      bridge: {
        degree: 3,
        bass: 'void',
        arp: 'spiral',
        lead: 'question',
        bell: 'omens',
        drums: 'none',
      },
      turn: {
        degree: 1,
        bass: 'ritual',
        arp: 'shards',
        lead: null,
        bell: 'ritual',
        drums: 'ritual',
      },
      lift: {
        degree: 4,
        bass: 'steps',
        arp: 'pulse',
        lead: 'theme',
        bell: 'tears',
        drums: 'ritual',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'resolve',
        bell: 'ritual',
        drums: 'credits',
      },
    },
  },
  {
    id: 'abyss-choir',
    title: '심연의 합창기',
    chapter: '엔딩 / 최종 보스',
    usage: '최종 보스전, 공백 법정 난입, 선택 직전 절정',
    summary: '종편 전부를 끌어올린 결전용 보스 테마다.',
    scene: '엔딩',
    accent: 'gold',
    palette: 'abyss',
    tempo: 138,
    tonicMidi: 50,
    mode: 'phrygian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'lift', 'resolve'],
    sections: {
      intro: { degree: 0, bass: 'march', arp: 'choir', lead: null, bell: 'ritual', drums: 'boss' },
      verse: {
        degree: 1,
        bass: 'chase',
        arp: 'pulse',
        lead: 'fracture',
        bell: null,
        drums: 'boss',
      },
      bridge: {
        degree: 6,
        bass: 'void',
        arp: 'spiral',
        lead: 'threat',
        bell: 'omens',
        drums: 'boss',
      },
      lift: { degree: 4, bass: 'chase', arp: 'pulse', lead: 'oath', bell: 'ritual', drums: 'boss' },
      resolve: {
        degree: 0,
        bass: 'march',
        arp: 'choir',
        lead: 'resolve',
        bell: 'ritual',
        drums: 'boss',
      },
    },
  },
  {
    id: 'ending-restored-dawn',
    title: '복원된 새벽',
    chapter: '엔딩 A',
    usage: '새벽종 복구 엔딩, 안정된 질서의 대가',
    summary: '안도와 상실이 동시에 남는, 밝지만 완전히 가볍지 않은 결말곡이다.',
    scene: '엔딩 A',
    accent: 'teal',
    palette: 'dawn',
    tempo: 74,
    tonicMidi: 60,
    mode: 'ionian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'resolve', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'ripple',
        lead: null,
        bell: 'glitter',
        drums: 'none',
      },
      verse: {
        degree: 4,
        bass: 'harbor',
        arp: 'ripple',
        lead: 'theme',
        bell: 'tears',
        drums: 'softPulse',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'choir',
        lead: 'question',
        bell: 'distant',
        drums: 'none',
      },
      lift: {
        degree: 3,
        bass: 'steps',
        arp: 'pulse',
        lead: 'horizon',
        bell: 'glitter',
        drums: 'credits',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'resolve',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
  {
    id: 'ending-unbound-tomorrow',
    title: '풀려난 내일',
    chapter: '엔딩 B',
    usage: '새벽종 해체 엔딩, 열린 하늘, 불안한 자유',
    summary: '해방감이 있지만 방향이 아직 정해지지 않은 결말을 넓게 남긴다.',
    scene: '엔딩 B',
    accent: 'gold',
    palette: 'orchard',
    tempo: 78,
    tonicMidi: 62,
    mode: 'lydian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'turn', 'resolve', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'orchard',
        lead: null,
        bell: 'glitter',
        drums: 'none',
      },
      verse: {
        degree: 1,
        bass: 'harbor',
        arp: 'glass',
        lead: 'bloom',
        bell: 'tears',
        drums: 'softPulse',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'ripple',
        lead: 'question',
        bell: 'distant',
        drums: 'none',
      },
      turn: {
        degree: 6,
        bass: 'void',
        arp: 'spiral',
        lead: 'horizon',
        bell: 'glitter',
        drums: 'none',
      },
      lift: {
        degree: 4,
        bass: 'steps',
        arp: 'pulse',
        lead: 'theme',
        bell: 'glitter',
        drums: 'credits',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'resolve',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
  {
    id: 'ending-last-anchor',
    title: '마지막 닻',
    chapter: '엔딩 C',
    usage: '플레이어 결속 엔딩, 희생과 잔향',
    summary: '가장 개인적인 상실과 세계 유지의 무게를 조용히 감싼다.',
    scene: '엔딩 C',
    accent: 'rose',
    palette: 'mist',
    tempo: 70,
    tonicMidi: 57,
    mode: 'dorian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'turn', 'verse', 'resolve', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'harborMist',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 5,
        bass: 'harbor',
        arp: 'choir',
        lead: 'lament',
        bell: 'tears',
        drums: 'none',
      },
      bridge: {
        degree: 3,
        bass: 'descent',
        arp: 'spiral',
        lead: 'question',
        bell: 'omens',
        drums: 'softPulse',
      },
      turn: {
        degree: 1,
        bass: 'void',
        arp: 'harborMist',
        lead: null,
        bell: 'ritual',
        drums: 'none',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'resolve',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
  {
    id: 'credits-echo-sea',
    title: '반향해 크레딧',
    chapter: '엔딩 / 크레딧',
    usage: '메인 크레딧, 후일담, 플레이 후 여운 정리',
    summary: '메인 테마를 가장 부드럽게 회수하는 크레딧 전용 트랙이다.',
    scene: '크레딧',
    accent: 'plum',
    palette: 'dawn',
    tempo: 80,
    tonicMidi: 59,
    mode: 'ionian',
    arrangement: ['intro', 'verse', 'bridge', 'verse', 'lift', 'verse', 'resolve', 'resolve'],
    sections: {
      intro: {
        degree: 0,
        bass: 'breath',
        arp: 'ripple',
        lead: null,
        bell: 'distant',
        drums: 'none',
      },
      verse: {
        degree: 4,
        bass: 'harbor',
        arp: 'ripple',
        lead: 'theme',
        bell: 'glitter',
        drums: 'credits',
      },
      bridge: {
        degree: 5,
        bass: 'descent',
        arp: 'choir',
        lead: 'horizon',
        bell: 'tears',
        drums: 'none',
      },
      lift: {
        degree: 3,
        bass: 'steps',
        arp: 'pulse',
        lead: 'resolve',
        bell: 'glitter',
        drums: 'credits',
      },
      resolve: {
        degree: 0,
        bass: 'breath',
        arp: 'choir',
        lead: 'resolve',
        bell: 'tears',
        drums: 'credits',
      },
    },
  },
];

function freezeTrack(track) {
  return Object.freeze({
    ...track,
    paletteSettings: Object.freeze(PALETTE_PRESETS[track.palette]),
    arrangement: Object.freeze([...track.arrangement]),
    sections: Object.freeze(
      Object.fromEntries(
        Object.entries(track.sections).map(([sectionName, section]) => [
          sectionName,
          Object.freeze({ ...section }),
        ])
      )
    ),
  });
}

export const bgmTrackCatalog = Object.freeze(
  TRACKS.map((track) =>
    Object.freeze({
      id: track.id,
      title: track.title,
      chapter: track.chapter,
      usage: track.usage,
      summary: track.summary,
      scene: track.scene,
      accent: track.accent,
      tempo: track.tempo,
      mode: track.mode,
    })
  )
);

export const BGM_TRACK_LIBRARY = Object.freeze(
  Object.fromEntries(TRACKS.map((track) => [track.id, freezeTrack(track)]))
);

export const DEFAULT_TRACK_ID = TRACKS[0].id;

export function getTrackDefinition(trackId) {
  return BGM_TRACK_LIBRARY[trackId] ?? BGM_TRACK_LIBRARY[DEFAULT_TRACK_ID];
}
